nodes = ['A', 'B','C','F','O','P','R','S']
weightedEdges = [
    ["Oradea","Zerind",71],
    ["Oradea","Sibiu",151],
    ["Zerind","Arad",75],
    ["Arad","Sibiu",140],
    ["Arad","Timisoara",118],
    ["Arad","Zerind",75],
    ["Sibiu","Fagaras",99],
    ["Sibiu","Rimnicu Vilcea",80],
    ["Sibiu","Arad",140],
    ["Sibiu","Oradea",151],
    ["Timisoara","Lugoj",111],
    ["Timisoara","Arad",118],
    ["Lugoj","Mehadia",70],
    ["Lugoj","Timisoara",111],
    ["Mehadia","Dobreta",75],
    #["Mehadia","Lugoj",70],
    ["Dobreta","Craiova",120],
    ["Dobreta","Mehadia",75],
    ["Rimnicu Vilcea","Craiova",146],
    ["Rimnicu Vilcea","Pitesti",97],
    ["Rimnicu Vilcea","Sibiu",80],
    ["Craiova","Pitesti",138],
    ["Craiova","Rimnicu Vilcea",146],
    ["Craiova","Dobreta",120],
    ["Pitesti","Bucharest",101],
    ["Pitesti","Craiova",138],
    ["Pitesti","Rimnicu Vilcea",97],
    ["Fagaras","Bucharest",211],
    ["Fagaras","Sibiu",99],
    ["Bucharest","Giurgiu",90],
    ["Bucharest","Urziceni",85],
    ["Giurgiu","Bucharest",90],
    ["Hirsova","Efoire",86],    
    ["Hirsova","Urziceni",98],    
    ["Urziceni","Hirsova",98],
    ["Urziceni","Vaslui",142],
    ["Urziceni","Bucharest",85],
    ["Vaslui","Iasi",92],
    ["Vaslui","Urziceni",142],
    ["Iasi","Neamt",87],
    ["Iasi","Vaslui",92],
    ["Neamt","Iasi",87],
    ["Efoire","Hirsova",86],
    

]
costToReachN = {
    "Arad":366,
    "Bucharest":0,
    "Craiova":160,
    "Dobreta":242,
    "Efoire":161,
    "Fagaras":176,
    "Giurgiu":77,
    "Hirsova":151,
    "Iasi":226,
    "Lugoj":244,
    "Mehadia":241,
    "Neamt":234,
    "Oradea":380,
    "Pitesti":10,
    "Rimnicu Vilcea":193,
    "Sibiu":253,
    "Timisoara":329,
    "Urziceni":80,
    "Vaslui":199,
    "Zerind":374
}
